#!/bin/sh

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources

xsetroot -solid grey
xterm -geometry 160x48+10+10 -ls -title "$VNCDESKTOP Desktop" &




